import components.simplereader.SimpleReader;
import components.simplereader.SimpleReader1L;
import components.simplewriter.SimpleWriter;
import components.simplewriter.SimpleWriter1L;
import components.xmltree.XMLTree;
import components.xmltree.XMLTree1;

/**
 * Program to convert an XML RSS (version 2.0) feed from a given URL into the
 * corresponding HTML output file.
 *
 * @author Praj Sachan
 *
 */
public final class RSSAggregator {

    /**
     * Private constructor so this utility class cannot be instantiated.
     */
    private RSSAggregator() {
    }

    /**
     * Outputs the "opening" tags in the generated HTML file. These are the
     * expected elements generated by this method:
     *
     * <html> <head> <title>the channel tag title as the page title</title>
     * </head> <body>
     * <h1>the page title inside a link to the <channel> link</h1>
     * <p>
     * the channel description
     * </p>
     * <table border="1">
     * <tr>
     * <th>Date</th>
     * <th>Source</th>
     * <th>News</th>
     * </tr>
     *
     * @param channel
     *            the channel element XMLTree
     * @param out
     *            the output stream
     * @updates out.content
     * @requires [the root of channel is a <channel> tag] and out.is_open
     * @ensures out.content = #out.content * [the HTML "opening" tags]
     */
    private static void outputHeader(XMLTree channel, SimpleWriter out) {
        assert channel != null : "Violation of: channel is not null";
        assert out != null : "Violation of: out is not null";
        assert channel.isTag() && channel.label().equals("channel")
                : "" + "Violation of: the label root of channel is a <channel> tag";
        assert out.isOpen() : "Violation of: out.is_open";

        // prints channel title onto page title
        XMLTree title = channel.child(getChildElement(channel, "title"));
        String header;
        if (title.numberOfChildren() > 0) {
            header = title.child(0).label();
        } else {
            header = "No Title Available";
        }
        out.println("<title>" + header + "</title> ");

        // more opening tags
        out.println("</head>");
        out.println("<body>");

        // gets content from link
        XMLTree link = channel.child(getChildElement(channel, "link"));
        String headerLink;
        if (link.numberOfChildren() > 0) {
            headerLink = link.child(0).label();
        } else {
            headerLink = "#";
        }
        out.println("<h1><a href = " + headerLink + ">" + header + "</a></h1>");

        // Output paragraph of description content
        XMLTree description = channel.child(getChildElement(channel, "description"));
        String descriptionContent;
        if (description.numberOfChildren() > 0) {
            descriptionContent = description.child(0).label();
        } else {
            descriptionContent = "No description available";
        }
        out.println("<p>" + descriptionContent + "</p>");

        // table and column header
        out.println("<table border=\"1\">");
        out.println("<tr>");
        out.println("<th>Date</th>");
        out.println("<th>Source</th>");
        out.println("<th>News</th>");
        out.println("</tr>");

    }

    /**
     * Outputs the "closing" tags in the generated HTML file. These are the
     * expected elements generated by this method:
     *
     * </table>
     * </body> </html>
     *
     * @param out
     *            the output stream
     * @updates out.contents
     * @requires out.is_open
     * @ensures out.content = #out.content * [the HTML "closing" tags]
     */
    private static void outputFooter(SimpleWriter out) {
        assert out != null : "Violation of: out is not null";
        assert out.isOpen() : "Violation of: out.is_open";

        out.println("</table>");
        out.println("</body>");
        out.println("</html>");

    }

    /**
     * Finds the first occurrence of the given tag among the children of the
     * given {@code XMLTree} and return its index; returns -1 if not found.
     *
     * @param xml
     *            the {@code XMLTree} to search
     * @param tag
     *            the tag to look for
     * @return the index of the first child of type tag of the {@code XMLTree}
     *         or -1 if not found
     * @requires [the label of the root of xml is a tag]
     * @ensures <pre>
     * getChildElement =
     *  [the index of the first child of type tag of the {@code XMLTree} or
     *   -1 if not found]
     * </pre>
     */
    private static int getChildElement(XMLTree xml, String tag) {
        assert xml != null : "Violation of: xml is not null";
        assert tag != null : "Violation of: tag is not null";
        assert xml.isTag() : "Violation of: the label root of xml is a tag";

        int index = 0, i = 0;
        //i iterates through tags while position returns the tag equal to user
        String name = xml.child(i).label();
        // if the tag doesn't match and is less than #of children, keep iterating
        while (!name.equals(tag) && i < xml.numberOfChildren()) {
            name = xml.child(i).label();
            if (name.equals(tag)) {
                index = i;
            }
            i++;
        }
        // if tag is not present, returns -1
        if (!name.equals(tag)) {
            index = -1;
        }
        return index;
    }

    /**
     * Processes one news item and outputs one table row. The row contains three
     * elements: the publication date, the source, and the title (or
     * description) of the item.
     *
     * @param item
     *            the news item
     * @param out
     *            the output stream
     * @updates out.content
     * @requires [the label of the root of item is an <item> tag] and
     *           out.is_open
     * @ensures <pre>
     * out.content = #out.content *
     *   [an HTML table row with publication date, source, and title of news item]
     * </pre>
     */
    private static void processItem(XMLTree item, SimpleWriter out) {
        assert item != null : "Violation of: item is not null";
        assert out != null : "Violation of: out is not null";
        assert item.isTag() && item.label().equals("item")
                : "" + "Violation of: the label root of item is an <item> tag";
        assert out.isOpen() : "Violation of: out.is_open";

        // Start table row
        out.println("<tr>");

        // Publication date
        String pubDate = getChildContent(item, "pubDate");
        if (pubDate.isEmpty()) {
            out.println("No publication date found");
        } else {
            out.println("<td>" + pubDate + "</td>"); //if present add to row
        }

        // Source content
        String sourceUrl = getAttribute(item, "source", "url");
        String source = getChildContent(item, "source");
        if (source.isEmpty() || sourceUrl.isEmpty()) {
            out.println("<td>No source found</td>");
        } else { // if present add to source row
            out.println("<td><a href=\"" + sourceUrl + "\">" + source + "</a></td>");
        }

        // News title or description with link
        String title = getChildContent(item, "title");
        String description = getChildContent(item, "description");
        String link = getChildContent(item, "link");

        // Use title if available, otherwise use description
        String content;
        if (!title.isEmpty()) {
            content = title;
        } else {
            content = description;
        }
        // if link is not present, use content
        if (link.isEmpty()) {
            out.println("<td>" + content + "</td>");
        } else {
            out.println("<td><a href=\"" + link + "\">" + content + "</a></td>");
        }

        // End table row
        out.println("</tr>");
    }

    /**
     * Helper Method to get content of child element by tag.
     *
     * @param item
     *            the news item
     *
     * @param tag
     *            the tag to look for
     *
     * @return result the string that is found as content from item
     *
     *
     */
    private static String getChildContent(XMLTree item, String tag) {
        String result = "";
        int index = getChildElement(item, tag);
        if (index != -1) { // if tag is present
            XMLTree childTag = item.child(index);
            // Check if the child has at least one child before accessing
            if (childTag.numberOfChildren() > 0) {
                result = childTag.child(0).label();
            }
        }
        return result;
    }

    /**
     * Helper Method to get attribute value from child element by tag.
     *
     * @param item
     *            the news item
     *
     * @param tag
     *            the tag to look for
     *
     * @param attributeName
     *            the value of attribute
     *
     * @return result the string that is found as content from item
     *
     */
    private static String getAttribute(XMLTree item, String tag, String attributeName) {
        String result = "";
        int index = getChildElement(item, tag);
        if (index != -1) { // if tag is present, return attribute value of it
            result = item.child(index).attributeValue(attributeName);
        }
        return result;
    }

    /**
     * Processes one XML RSS (version 2.0) feed from a given URL converting it
     * into the corresponding HTML output file.
     *
     * @param url
     *            the URL of the RSS feed
     * @param file
     *            the name of the HTML output file
     * @param out
     *            the output stream to report progress or errors
     * @updates out.content
     * @requires out.is_open
     * @ensures <pre>
     * [reads RSS feed from url, saves HTML document with table of news items
     *   to file, appends to out.content any needed messages]
     * </pre>
     */
    private static void processFeed(String url, String file, SimpleWriter out) {
        XMLTree xml = new XMLTree1(url);
        if (xml.label().equals("rss") && xml.hasAttribute("version")
                && xml.attributeValue("version").equals("2.0")) {

            //channel element and output header
            XMLTree channel = xml.child(0);
            //write to separate HTML file
            SimpleWriter outfile = new SimpleWriter1L(file);

            outputHeader(channel, outfile);

            //loop through each source
            for (int i = 0; i < channel.numberOfChildren(); i++) {
                if (channel.child(i).label().equals("item")) {
                    processItem(channel.child(i), outfile);
                }
            }
            outfile.println("</table>");

            //output footer and close file
            outputFooter(outfile);
            outfile.close();
        } else {
            out.println("Invalid RSS feed");
        }

    }

    /**
     * Main method.
     *
     * @param args
     *            the command line arguments; unused here
     */
    public static void main(String[] args) {
        SimpleReader in = new SimpleReader1L();
        SimpleWriter out = new SimpleWriter1L();

        //Input for xml file
        out.print("Enter the name of xml file: ");
        String userUrl = in.nextLine();
        XMLTree xml = new XMLTree1(userUrl);

        //output for HTML
        out.println("Enter a name for output file: ");
        String fileName = in.nextLine();
        SimpleWriter fileOut = new SimpleWriter1L(fileName);

        //Main html structure
        fileOut.println("<html><head><title>Top Stories</title></head><body>");
        fileOut.println("<h1>Top Stories</h1>");
        fileOut.println("<ul>");

        //Process each ULR from xml
        for (int i = 0; i < xml.numberOfChildren(); i++) {
            XMLTree urlElement = xml.child(i);
            if (urlElement.label().equals("feed")) {
                //
                String feedUrl = urlElement.attributeValue("url");
                String feedFile = "feed" + i + ".html";

                // Process the RSS feed and create HTML output
                processFeed(feedUrl, feedFile, out);

                // Add a link to the index file
                fileOut.println(
                        "<li><a href=\"" + feedFile + "\">" + feedUrl + "</a></li>");
            }
        }
        fileOut.println("</ul></body></html>");
        in.close();
        out.close();
        fileOut.close();
    }

}
